[build]
  node_version = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[scheduled_functions]]
  function = "send-email-delete-dates-reminder"
  schedule = "0 0 1 * *"